config/routes.rb
Rails.application.routes.draw do
  root to: "ekkos#index"
  devise_for :users

  resources :ekkos, only: [:index]
  resources :users, only: [:show, :index] do
    collection do
      get :search
      get :following
    end
  end

  resources :relationships, only: [:create, :destroy]

  get "search_soundcloud" => "soundcloud#search"
  get "record_soundcloud" => "soundcloud#record"
  post "import_soundcloud_user" => "soundcloud#import_user"
end

app/models/echo.rb
class Ekko < ActiveRecord::Base
end

app/models/ekko.rb
class Ekko < ActiveRecord::Base
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
  validates :username, presence: true
  has_many :followed_users, through: :relationships, source: :followed
  has_many :relationships, foreign_key: "follower_id",
    dependent: :destroy

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id).present?
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :setup_soundcloud_client

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # user soundcloud client
  def setup_soundcloud_client
    @client = SoundCloud.new({
      :client_id     => ENV['soundcloud_client_id'],
      :client_secret => ENV['soundcloud_client_secret'],
      :username      => ENV['soundcloud_username'],
      :password      => ENV['soundcloud_password']
    })
  end
end

app/controllers/ekkos_controller.rb
class EkkosController < ApplicationController
  def show
  end

  def index
    #todo: get only public tracks
    @ekkos = @client.get("/me/tracks")

    current_user.followed_users.each do |user|
      user_tracks_hash = @client.get("/users/#{user.soundcloud_id}/tracks")
      @ekkos.concat(user_tracks_hash)
    end

    @ekkos.delete_if {|ekko| ekko.sharing != "public"}

    #@ekkos.sort! { |a,b| b['id'] <=> a['id'] }
    @ekkos = @ekkos.paginate(page: params[:page], per_page: 4)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @user = User.find(params[:relationship][:followed_id])
    current_user.follow!(@user)
    redirect_to :back, notice: "You are now following #{@user.username}"
  end

  def destroy
    @user = User.find(params[:relationship][:followed_id])
    current_user.unfollow!(@user)
    redirect_to :back, notice: "You just unfollowed #{@user.username}"
  end
end

app/controllers/soundcloud_controller.rb
class SoundcloudController < ApplicationController
  def record

  end

  def search
    if params["query"].present?
      @soundcloud_users = @client.
        get('/users', q: params["query"])
    else
      @soundcloud_users = []
    end
  end

  def import_user
    user = User.new(soundcloud_id: params[:soundcloud_id])
    user.username = params[:username]
    user.password = ENV["default_user_password"]
    user.email = "#{params[:permalink]}@soundcloud.com"
    user.save!

    redirect_to :back
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def search
  end

  def index
    @users = User.all
  end

  def following
    user = current_user
    @users = user.followed_users
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ekkos/index.html.erb
<% @ekkos.each do |ekko| %>
  <p>
    <% embed_info = @client.get('/oembed',
                                url: ekko.uri,
                                maxheight: 130,
                                maxwidth: 500) %>
    <%= embed_info['html'].html_safe %>
  </p>
<% end %>

<%= will_paginate @ekkos, renderer: BootstrapPagination::Rails %>

app/views/ekkos/show.html.erb
<h1>Echo#show</h1>
<p>Find me in app/views/echo/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ekko</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Ekkos", ekkos_path %></li>
        <li><%= link_to "Search Soundcloud", search_soundcloud_path %></li>
        <li><%= link_to "Following", following_users_path %></li>
        <li><%= link_to "Record", record_soundcloud_path %></li>
      </ul>

      <div class="pull-right user-info">
        <ul class="nav nav-tabs">
          <% if current_user %>
            <li><%= link_to current_user.username, user_path(current_user) %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign In", new_user_session_path %> or </li>
            <li><%= link_to "Sign Up", new_user_registration_path %> <li>
          <% end %>
        </ul>
      </div>
    </div>

    <div class="container">
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:error] %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:error] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>

      <br/>
      <br/>
      <br/>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: user.id)) do |f| %>
  <%= f.hidden_field :followed_id %>
  <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_follow_form.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= render partial: 'shared/unfollow', locals: {user: user} %>
  <% else %>
    <%= render partial: 'shared/follow', locals: {user: user} %>
  <% end %>
<% end %>

app/views/shared/_profile.html.erb
<%= user.username %>
<%= link_to user.username, user_path(user) %>
<%= user.email %>
<% if signed_in? %>
  <%= render partial: "shared/follow_form", locals: {user: @user} %>
<% end %>

app/views/shared/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by(followed_id: user.id),
             html: { method: :delete }) do |f| %>
  <%= f.hidden_field :followed_id %>
  <%= f.submit "Unfollow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/soundcloud/_import.html.erb
<%= form_tag(import_soundcloud_user_path, method: :post) do %>
  <%= hidden_field_tag :soundcloud_id, user.id %>
  <%= hidden_field_tag :username, user.username %>
  <%= hidden_field_tag :permalink, user.permalink %>
  <%= submit_tag "Import", class: "btn btn-large btn-primary" %>
<% end %>

app/views/soundcloud/_import_form.html.erb
<% user_by_soundcloud_id = User.find_by(soundcloud_id: user.id) %>
<% if user_by_soundcloud_id.nil? %>
  <%= render partial: "import", locals: {user: user} %>
<% else %>
  <%= render partial: "shared/follow_form", locals: {user: user_by_soundcloud_id} %>
<% end %>

app/views/soundcloud/_soundcloud_user_table.html.erb
<div class="table-responsive">
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>Username (full name)</th>
        <th>Status</th>
      </tr>
    </thead>
    <body>
      <% soundcloud_users.each do |user| %>
        <tr>
          <td>
            <%= user.username %>
            <% if user.full_name.present? %>
              <%= " (" + user.full_name + ")" %>
            <% end %>
          </td>
          <td>
            <%= render partial: "import_form", locals: {user: user} %>
          </td>
        </tr>
      <% end %>
    </body>
  </table>
</div>

app/views/soundcloud/record.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
<title>Recorder and Connect With SoundCloud</title>
<link rel="stylesheet" type="text/css" href="example.css" />
</head>
<body>
<script type="text/javascript" src="http://connect.soundcloud.com/2/latest.min.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js"></script>
<script type="text/javascript" src="recorder.js"></script>

<script>

Recorder.initialize({
  alert("inside")
  swfSrc: "recorder.swf"
  alert("done")
});


function record(){
  alert ("what's going on")
  Recorder.record({
    start: function(){
    alert("recording starts now. press stop when youre done. and then play or upload if you want.");
    },
    progress: function(milliseconds){
    document.getElementById("time").innerHTML = timecode(milliseconds);
    }
  });
}

function play(){
Recorder.stop();
Recorder.play({
progress: function(milliseconds){
document.getElementById("time").innerHTML = timecode(milliseconds);
}
});
}
function stop(){
Recorder.stop();
}
function upload(){
SC.connect({
client_id: "aHT5HITYm8vlkWNabL0Qg",
redirect_uri: "http://recorder.dev/examples/soundcloud-callback.html",
connected: function(){
Recorder.upload({
url: "https://api.soundcloud.com/tracks.json?oauth_token=" + SC.options.access_token,
audioParam: "track[asset_data]",
params: {
"track[title]": "recorder.js track test",
"track[sharing]": "private"
},
success: function(responseText){
var track = $.parseJSON(responseText)
window.location = track.permalink_url;
}
});
},
error: function(err){
alert(err)
}
})
}
</script>
<div id="wrapper">
<h1><a href="http://github.com/jwagener/recorder">Recorder Example</a></h1>
<p>
This is a very basic example for the Recorder.js.
Checkout <a href="http://github.com/jwagener/recorder">GitHub</a> for details and have a look at the source for this file.
Start by clicking record:
</p>
<div>
<a href="javascript:record()" id="record" >Record</a>
<a href="javascript:play()" id="play" >Play</a>
<a href="javascript:stop()" id="stop" >Stop</a>
<a href="javascript:upload()" id="upload" >Upload to SoundCloud</a>
</div>
<span id="time">0:00</span>
</div>
</body>
</html>

app/views/soundcloud/search.html.erb
<div class="panel-heading">
  <%= form_tag(search_soundcloud_path, method: :get) do %>
    <%= text_field_tag :query, params[:query] %>
    <%= submit_tag "Search", class: "btn btn-default" %>
  <% end %>
</div>

<br/>

<div class="col-md-10 col-xs-12 col-sm-9">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default">
        <%= render partial: "soundcloud_user_table", locals: {soundcloud_users: @soundcloud_users} %>
      </div>
    </div>
  </div>
</div>

app/views/soundcloud/users.html.erb
<div class="col-md-10 col-xs-12 col-sm-9">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default">
        <%= render partial: "soundcloud_user_table", locals: {soundcloud_users: @soundcloud_users} %>
      </div>
    </div>
  </div>
</div>

app/views/users/_user_table.html.erb
<div class="table-responsive">
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>Username (full name)</th>
        <th>Status</th>
      </tr>
    </thead>
    <body>
      <% users.each do |user| %>
        <tr>
          <td>
            <%= user.username %>
          </td>
          <td>
            <%= render partial: "shared/follow_form", locals: {user: user} %>
          </td>
        </tr>
      <% end %>
    </body>
  </table>
</div>

app/views/users/following.html.erb
<div class="col-md-10 col-xs-12 col-sm-9">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default">
        <%= render partial: "user_table", locals: {users: @users } %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <%= user.email %>
<% end %>

app/views/users/search.html.erb
<div class="panel-heading">
  <%= form_tag(users_path, method: :get, class: "pull-right") do %>
    <%= text_field_tag :query, params[:query] %>
    <%= submit_tag "Search", class: "btn btn-default" %>
  <% end %>
</div>

app/views/users/show.html.erb
<%= render partial: "shared/profile", locals: {user: @user} %>